[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hipsc-superdeformability"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["src"]

